# Generated by Django 3.2.6 on 2021-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0002_auto_20211009_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedata',
            name='edNodeOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuedata',
            name='stNodeOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driveraccount',
            name='cityCode',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
    ]
