# Generated by Django 3.2.6 on 2021-10-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0003_auto_20211009_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeperbus',
            name='busRouteId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routeperbus',
            name='nodeId',
            field=models.CharField(max_length=50),
        ),
    ]
