# Generated by Django 3.2.6 on 2021-10-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0005_auto_20211010_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeperbus',
            name='busRouteId',
            field=models.ForeignKey(db_column='busRouteId', on_delete=django.db.models.deletion.DO_NOTHING, to='pnsApp.routedata'),
        ),
        migrations.AlterField(
            model_name='routeperbus',
            name='nodeId',
            field=models.ForeignKey(db_column='nodeId', on_delete=django.db.models.deletion.DO_NOTHING, to='pnsApp.busstationdata'),
        ),
    ]
