# Generated by Django 3.2.6 on 2021-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0006_auto_20211010_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeperbus',
            name='nodeord',
            field=models.IntegerField(default=0),
        ),
    ]
