# Generated by Django 3.2.6 on 2021-10-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0010_alter_queuedata_boardingcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveraccount',
            name='cityCode',
        ),
    ]
