# Generated by Django 3.2.6 on 2021-10-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0011_remove_driveraccount_citycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='queuedata',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_data', serialize=False, to='pnsApp.passengeraccount'),
        ),
    ]
