# Generated by Django 3.2.6 on 2021-10-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0012_auto_20211011_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedata',
            name='uid',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pnsApp.passengeraccount'),
        ),
    ]
