# Generated by Django 3.2.6 on 2021-10-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnsApp', '0013_alter_queuedata_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveraccount',
            name='pushSetting',
        ),
        migrations.RemoveField(
            model_name='driveraccount',
            name='pushToken',
        ),
        migrations.RemoveField(
            model_name='driveraccount',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='passengeraccount',
            name='pushSetting',
        ),
        migrations.RemoveField(
            model_name='passengeraccount',
            name='pushToken',
        ),
    ]
